version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      TZ: "UTC"
      MYSQL_ROOT_PASSWORD: UyNh4eve@6514
      MYSQL_ROOT_HOST: 'db'
    volumes:
      - ./MYSQL_Query:/docker-quaries

  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: UyNh4eve@6514
      MYSQL_DATABASE: bucketlist
    command: python app.py
#networks:
  #default:
    #driver: bridge



