apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: TXlQYXNzd29yZGhlYmE=  # encryption "MyPassword" by base64 
  MYSQL_NAME: QnVja2V0TGlzdA==  # encryption "BucketList" by base64